### ISSUE TITLE
abseil on windows, and a speed up of the abseil compilation

### ISSUE THREAD

**Issue by meshula** [hexops/dawn#2]
I figure this will be useful when you dig into a windows compilation. I have a cmake project that looks a lot like mach: (https://github.com/meshula/LabSlang)

During iteration, I've been frustrated that the official CMakeLists.txt from the abseil project is one of the biggest time consumers of the build, and for such a small value to the project.

I made a little shim project, and managed to organize abseil into almost a single-header-library. I got the abseil portion part of the glfw/dawn/tint build down from minutes to seconds.

There were some peculiarities in dawn's CMakeLists.txt that I sorted out which required the library to be broken into two specific. This wouldn't be necessary for mach's zig build.

It was a bit of a puzzle to organize the `.cc` files so they don't conflict with each other, and I needed to set the `WINDOWS_LEAN_AND_MEAN` and `NOMINMAX` macros. There's no significance to the file names I used, they are just left over from the thought process I had when I was trying to find the minimum organization of includes that would work.

I expect the single-header version of abseil will benefit the mach build, and the macros will be needed when you start the windows port. 

Please feel free to borrow anything you want from what I did. It's here:

https://github.com/meshula/LabSlang/tree/main/abseil

I think adding my cpp files to this repo, and building those instead of the direct abseil files would be a speed win, and a start on a windows port.

**Comment by slimsag** [comment]
@meshula really, thank you a ton for sending this, it's super interesting info and very timely.

> I got the abseil portion part of the glfw/dawn/tint build down from minutes to seconds.

Are you suggesting here that out of all the Dawn compilation (including dependencies), abseil takes _minutes_ on its own? That's insane and I really wouldn't have expected that at all! Especially given Dawn itself seems to take just, what, like 5-10 minutes overall to compile? Very curious if you have any more concrete numbers around this, I'll be trying to gather them myself as well

---

The header-only abseil approach is interesting. I'm not sure I fully understand so I'm hoping you can help me:

* Why does a header-only approach end up being faster to compile? From what I can tell you are `#include`ing all the same files, so I'm not sure I follow why that would be faster to compile than going abseil->lib->linking - maybe it's reducing the amount of abseil code included in the final lib so you avoid linker times or something?

* Did your structuring of `numbers`, `str-format`, and `strings` have a meaningful reason behind it? Why not place all #include in a single file?

**Comment by meshula** [comment]
I'll try to do some timing later. 

1. why faster? 

When you cmake, specifically, on Windows, the abseil build is comprised of 52 individual  targets, each with one or two files in it. Each target takes several seconds for the build system to visit, and that's why it takes minutes. Glomming all the files together means that the build is paying for three start ups.

I don't know how much this problem is due to cmake or msbuild ~ it feels like both treat abseil in a pathological way, **it may be irrelevant for `zig build`.**

2. The cmake files for dawn explicitly link `strings.lib`, and `str-format.lib`. I needed therefore two non-empty libs to satisfy dawn's cmake, because my goal was to not have to patch dawn in any way. `numbers` came about because absl-numbers has many conflicts when globbed with the files in str-format, and at first I thought it might make sense to move all of it out.

3. A combination of logic and intuition based on experience with other giant monster libs like boost and folly. It took a couple of hours, until I got a working dawn build with no symbols duplicated or missing.

**Comment by meshula** [comment]
some measurements:

win10 desktop
---------------

cmake + msbuild / 9 minutes
cmake + msbuild + abseil_unity / 8 minutes

abseil cmake / 1 minute
abseil unity / 2.5s

dawn/gpu zig build, fast win10 build fails in abseil due to pthreads

mac desktop
-------------

cmake + xcode, / 4 minutes
cmake + xcode + abseil_unity / 3 minutes 30 seconds

abseil cmake / 30 seconds
abseil unity / 1.5s

dawn/gpu zig build, fast mac, 5m 12s

**Comment by slimsag** [comment]
Thanks a TON for the info here, this is all super useful for me
